apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: multistep-pipeline
spec:
  description: |
    A sample pipeline that runs three echo tasks sequentially,
    followed by three finally tasks for cleanup or reporting.
  tasks:
    - name: echo-task-1
      taskSpec:
        steps:
          - name: step-1
            image: alpine:latest
            script: |
              #!/bin/sh
              echo "Running Task 1"
              sleep 5

    - name: echo-task-2
      runAfter:
        - echo-task-1
      taskSpec:
        steps:
          - name: step-2
            image: alpine:latest
            script: |
              #!/bin/sh
              echo "Running Task 2"
              sleep 20

    - name: echo-task-3
      runAfter:
        - echo-task-2
      taskSpec:
        steps:
          - name: step-3
            image: alpine:latest
            script: |
              #!/bin/sh
              echo "Running Task 3"
              sleep 10
