apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: echo-pipeline
  namespace: apalit
spec:
  description: |
    A sample pipeline that runs three echo tasks sequentially,
    followed by three finally tasks for cleanup or reporting.
  tasks:
    - name: echo-task-1
      taskSpec:
        steps:
          - name: step-1
            image: alpine:latest
            script: |
              #!/bin/sh
              echo "Running Task 1"

    - name: echo-task-2
      runAfter:
        - echo-task-1
      taskSpec:
        steps:
          - name: step-2
            image: alpine:latest
            script: |
              #!/bin/sh
              echo "Running Task 2"

    - name: echo-task-3
      runAfter:
        - echo-task-2
      taskSpec:
        steps:
          - name: step-3
            image: alpine:latest
            script: |
              #!/bin/sh
	      sleep 10
              echo "Running Task 3"

  finally:
    - name: final-echo-1
      taskSpec:
        steps:
          - name: final-step-1
            image: alpine:latest
            script: |
              #!/bin/sh
              echo "Finally Task 1 - cleanup"

    - name: final-echo-2
      taskSpec:
        steps:
          - name: final-step-2
            image: alpine:latest
            script: |
              #!/bin/sh
              echo "Finally Task 2 - notify"

    - name: final-echo-3
      taskSpec:
        steps:
          - name: final-step-3
            image: alpine:latest
            script: |
              #!/bin/sh
              echo "Finally Task 3 - wrap-up"
