apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: 3-level-nesting-child-pipeline
  namespace: apalit
spec:
  params:
    - name: message
      type: string
  tasks:
    - name: run-grandchild
      pipelineRef:
        name: 3-level-nesting-grandchild-pipeline
      params:
        - name: message
          value: $(params.message)
